### ISSUE TITLE
"Too few arguments to function Snowfire\Beautymail\Beautymail::__construct(), 0 passed in 

### ISSUE THREAD

**Issue by sherinmac** [Snowfire/Beautymail#102]
use Snowfire\Beautymail\Beautymail;
$beautymail = new Beautymail;
 $beautymail->to($enquiry->customer_email)->send(new Enquirymail($enquiry));

I use this code in controller   and i  gett this error 
Too few arguments to function Snowfire\Beautymail\Beautymail::__construct(), 0 passed in

**Comment by JustAMurph** [comment]
BeautyMail expects a `$settings` parameter. Try resolving the instance out of the container instead like:

`$beautymail = app()->make(Snowfire\Beautymail\Beautymail::class);`
