### ISSUE TITLE
@mail.ru Emails are not Delivered

### ISSUE THREAD

**Issue by Madhackers21** [Snowfire/Beautymail#103]
Hello

Everything works Great, Fantastic!!
But when I change:

`->from('bar@example.com')` With `->from('anytestemail@mail.ru')`
I`m not receiving any Email :/
Error in Webmail:

host gmail-smtp-in.l.google.com [64.233.166.26]
    SMTP error from remote mail server after end of data:
    550-5.7.1 Unauthenticated email from mail.ru is not accepted due to domain's
    550-5.7.1 DMARC policy. Please contact the administrator of mail.ru domain if
    550-5.7.1 this was a legitimate mail. Please visit
    550-5.7.1  https://support.google.com/mail/answer/2451690 to learn about the
    550 5.7.1 DMARC initiative. s8si12659191wrn.0 - gsmtp

What Can be a Problem here?

**Comment by emilsundberg** [comment]
I don't think this has anything to do with Beautymail. I would suggest using an ESP such as Postmark/Sendgrid to send your emails.
