### ISSUE TITLE
Error when after install and config this package

### ISSUE THREAD

**Issue by wrtisans** [Snowfire/Beautymail#109]
`"message": "array_merge(): Expected parameter 1 to be an array, null given",
    "exception": "ErrorException",
    "file": "/Users/username/workspace/php/theo/vendor/snowfire/beautymail/src/Snowfire/Beautymail/BeautymailServiceProvider.php",
    "line": 53,`

php 7.3,
laravel 5.8

**Comment by althafn96** [comment]
Did you get a solution for this yet?

**Comment by wrtisans** [comment]
Nop, i think this package was deprecated ...

**Comment by dhduc** [comment]
You can check this out:
[https://github.com/Snowfire/Beautymail/issues/110#issuecomment-529204500](https://github.com/Snowfire/Beautymail/issues/110#issuecomment-529204500)
