### ISSUE TITLE
Pelago\Emogrifier dependency now broken

### ISSUE THREAD

**Issue by benjamin-ndc** [Snowfire/Beautymail#111]
For one you have it set to `'@dev'`.

They just released a new version a couple of hours ago, and removed a function that your package was using.

```
In CssInlinerPlugin.php line 18:
                                                                             
  Call to undefined method Pelago\Emogrifier::disableInvisibleNodeRemoval()  
```

You'll have to set that dependency to use `"pelago\emogrifie": "2.2.0"`, otherwise now anyone using your package will have a broken install.

**Comment by vesper8** [comment]
Thanks for a fix. Small typo though (backward slash and missing 'r')

`"pelago/emogrifier": "2.2.0",`

**Comment by hoanguel** [comment]
I am having exactly the issue that @benjamin-ndc  described above with my laravel app which now stopped running. What should I do to fix? Thanks!

**Comment by benjamin-ndc** [comment]
@hoanguel I had to remove this dependency, it turns out it wasn't being used by my project anyway. Obv not a real solution if you're using it, maybe submit a PR to this project to update composer.json with the above fix...

**Comment by vesper8** [comment]
the fix above works just fine for me

Either do that, or fork the project and replace the @dev in the composer.json by 2.2.0

obviously just adding `"pelago/emogrifier": "2.2.0",` to your own composer.json is a much easier fix

**Comment by emilsundberg** [comment]
Thanks. This issue has now been solved with #112

**Comment by gfernandez-me** [comment]
not working

**Comment by CitizenBeta** [comment]
I'm still running into this issue. 

> In CssInlinerPlugin.php line 18:
>                                                                              
>   Call to undefined method Pelago\Emogrifier::disableInvisibleNodeRemoval()
