### ISSUE TITLE
podrian agregarle la opcion de ReplyTo a la clase Beautymail

### ISSUE THREAD

**Issue by mestelles** [Snowfire/Beautymail#114]
in class BeautyMail
 public function replyTo($users)
    {
        return (new PendingMail($this))->replyTo($users);
    }
in  ```
class PendingMail
 public function replyTo($users)
    {
        $this->replyTo = $users;
        return $this;
    }
 protected function fill(Mailable $mailable)
    {
        return $mailable->to($this->to)
                        ->cc($this->cc)
                        ->bcc($this->bcc)
                        ->replyTo($this->replyTo);

    }
```

**Comment by emilsundberg** [comment]
Hi 👋 

Please open your issue in English
