### ISSUE TITLE
could you add the ReplyTo option to the class Beautymail

### ISSUE THREAD

**Issue by mestelles** [Snowfire/Beautymail#115]
in class BeautyMail
public function replyTo($users)
{
return (new PendingMail($this))->replyTo($users);
}
in ```
class PendingMail
public function replyTo($users)
{
$this->replyTo = $users;
return $this;
}
protected function fill(Mailable $mailable)
{
return $mailable->to($this->to)
->cc($this->cc)
->bcc($this->bcc)
->replyTo($this->replyTo);

}

**Comment by emilsundberg** [comment]
This is how you send a beautymail with replyTo:

```php
$beautymail = app()->make(Snowfire\Beautymail\Beautymail::class);
$beautymail->send('emails.welcome', [], function($message) {
    $message
        ->from('bar@example.com')
        ->to('foo@example.com', 'John Smith')
        ->replyTo('foobar@example.com')
        ->subject('Welcome!');
});
```
