### ISSUE TITLE
Doesn't work with latest Homestead / PHP 7.4

### ISSUE THREAD

**Issue by Binternet** [Snowfire/Beautymail#116]
The latest homestead comes with php7.4 by default.
You need to use php7.2 in order to get Beautymail and its dependancies to play nicely.

You need to use `php7.2` binary to run composer as a workaround:
`php7.2 /usr/local/bin/composer require snowfire/beautymail dev-master`

If that doesnt work just make sure these packages appear in `composer.json`:

```
    "require": {
        "php": "^7.2",
        "fideloper/proxy": "^4.0",
        "guzzlehttp/guzzle": "^6.5",
        "laravel/framework": "^6.2",
        "laravel/tinker": "^2.0",
        "pelago/emogrifier": "2.2.0",
        "snowfire/beautymail": "dev-master"
    }
```

And then fire:
`$ php7.2 /usr/local/bin/composer update`

**Comment by emilsundberg** [comment]
I've just tagged a release of Beautymail which supports PHP 7.4
