### ISSUE TITLE
When I am trying to install showing this problem. How I will solve this issue.

### ISSUE THREAD

**Issue by RakibRizan** [Snowfire/Beautymail#118]
Microsoft Windows [Version 10.0.18362.592]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\xampp\htdocs\project test\agrobint-test>composer require snowfire/beautymail dev-master
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - snowfire/beautymail dev-master requires pelago/emogrifier 2.2.0 -> satisfiable by pelago/emogrifier[v2.2.0].
    - Installation request for snowfire/beautymail dev-master -> satisfiable by snowfire/beautymail[dev-master].
    - Conclusion: remove symfony/css-selector v5.0.2
    - Conclusion: don't install symfony/css-selector v5.0.2
    - pelago/emogrifier v2.2.0 requires symfony/css-selector ^3.4.0 || ^4.0.0 -> satisfiable by symfony/css-selector[3.4.x-dev, 4.0.x-dev, 4.1.x-dev, 4.2.x-dev, 4.3.x-dev, 4.4.x-dev, v3.4.0, v3.4.0-BETA1, v3.4.0-BETA2, v3.4.0-BETA3, v3.4.0-BETA4, v3.4.0-RC1, v3.4.0-RC2, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.16, v3.4.17, v3.4.18, v3.4.19, v3.4.2, v3.4.20, v3.4.21, v3.4.22, v3.4.23, v3.4.24, v3.4.25, v3.4.26, v3.4.27, v3.4.28, v3.4.29, v3.4.3, v3.4.30, v3.4.31, v3.4.32, v3.4.33, v3.4.34, v3.4.35, v3.4.36, v3.4.37, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9, v4.0.0, v4.0.0-BETA1, v4.0.0-BETA2, v4.0.0-BETA3, v4.0.0-BETA4, v4.0.0-RC1, v4.0.0-RC2, v4.0.1, v4.0.10, v4.0.11, v4.0.12, v4.0.13, v4.0.14, v4.0.15, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9, v4.1.0, v4.1.0-BETA1, v4.1.0-BETA2, v4.1.0-BETA3, v4.1.1, v4.1.10, v4.1.11, v4.1.12, v4.1.2, v4.1.3, v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9, v4.2.0, v4.2.0-BETA1, v4.2.0-BETA2, v4.2.0-RC1, v4.2.1, v4.2.10, v4.2.11, v4.2.12, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9, v4.3.0, v4.3.0-BETA1, v4.3.0-BETA2, v4.3.0-RC1, v4.3.1, v4.3.10, v4.3.11, v4.3.2, v4.3.3, v4.3.4, v4.3.5, v4.3.6, v4.3.7, v4.3.8, v4.3.9, v4.4.0, v4.4.0-BETA1, v4.4.0-BETA2, v4.4.0-RC1, v4.4.1, v4.4.2, v4.4.3, v4.4.4].
    - Can only install one of: symfony/css-selector[3.4.x-dev, v5.0.2].
    - Can only install one of: symfony/css-selector[4.0.x-dev, v5.0.2].
    - Can only install one of: symfony/css-selector[4.1.x-dev, v5.0.2].
    - Can only install one of: symfony/css-selector[4.2.x-dev, v5.0.2].
    - Can only install one of: symfony/css-selector[4.3.x-dev, v5.0.2].
    - Can only install one of: symfony/css-selector[4.4.x-dev, v5.0.2].
    - Can only install one of: symfony/css-selector[v3.4.0, v5.0.2].
    - Can only install one of: symfony/css-selector[v3.4.0-BETA1, v5.0.2].
    - Can only install one of: symfony/css-selector[v3.4.0-BETA2, v5.0.2].
    - Can only install one of: symfony/css-selector[v3.4.0-BETA3, v5.0.2].
    - Can only install one of: symfony/css-selector[v3.4.0-BETA4, v5.0.2].
    - Can only install one of: symfony/css-selector[v3.4.0-RC1, v5.0.2].
    - Can only install one of: symfony/css-selector[v3.4.0-RC2, v5.0.2].
    - Can only install one of: symfony/css-selector[v3.4.1, v5.0.2].
    - Can only install one of: symfony/css-selector[v3.4.10, v5.0.2].
    - Can only install one of: symfony/css-selector[v3.4.11, v5.0.2].
    - Can only install one of: symfony/css-selector[v3.4.12, v5.0.2].
    - Can only install one of: symfony/css-selector[v3.4.13, v5.0.2].
    - Can only install one of: symfony/css-selector[v3.4.14, v5.0.2].
    - Can only install one of: symfony/css-selector[v3.4.15, v5.0.2].
    - Can only install one of: symfony/css-selector[v3.4.16, v5.0.2].
    - Can only install one of: symfony/css-selector[v3.4.17, v5.0.2].
    - Can only install one of: symfony/css-selector[v3.4.18, v5.0.2].
    - Can only install one of: symfony/css-selector[v3.4.19, v5.0.2].
    - Can only install one of: symfony/css-selector[v3.4.2, v5.0.2].
    - Can only install one of: symfony/css-selector[v3.4.20, v5.0.2].
    - Can only install one of: symfony/css-selector[v3.4.21, v5.0.2].
    - Can only install one of: symfony/css-selector[v3.4.22, v5.0.2].
    - Can only install one of: symfony/css-selector[v3.4.23, v5.0.2].
    - Can only install one of: symfony/css-selector[v3.4.24, v5.0.2].
    - Can only install one of: symfony/css-selector[v3.4.25, v5.0.2].
    - Can only install one of: symfony/css-selector[v3.4.26, v5.0.2].
    - Can only install one of: symfony/css-selector[v3.4.27, v5.0.2].
    - Can only install one of: symfony/css-selector[v3.4.28, v5.0.2].
    - Can only install one of: symfony/css-selector[v3.4.29, v5.0.2].
    - Can only install one of: symfony/css-selector[v3.4.3, v5.0.2].
    - Can only install one of: symfony/css-selector[v3.4.30, v5.0.2].
    - Can only install one of: symfony/css-selector[v3.4.31, v5.0.2].
    - Can only install one of: symfony/css-selector[v3.4.32, v5.0.2].
    - Can only install one of: symfony/css-selector[v3.4.33, v5.0.2].
    - Can only install one of: symfony/css-selector[v3.4.34, v5.0.2].
    - Can only install one of: symfony/css-selector[v3.4.35, v5.0.2].
    - Can only install one of: symfony/css-selector[v3.4.36, v5.0.2].
    - Can only install one of: symfony/css-selector[v3.4.37, v5.0.2].
    - Can only install one of: symfony/css-selector[v3.4.4, v5.0.2].
    - Can only install one of: symfony/css-selector[v3.4.5, v5.0.2].
    - Can only install one of: symfony/css-selector[v3.4.6, v5.0.2].
    - Can only install one of: symfony/css-selector[v3.4.7, v5.0.2].
    - Can only install one of: symfony/css-selector[v3.4.8, v5.0.2].
    - Can only install one of: symfony/css-selector[v3.4.9, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.0.0, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.0.0-BETA1, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.0.0-BETA2, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.0.0-BETA3, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.0.0-BETA4, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.0.0-RC1, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.0.0-RC2, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.0.1, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.0.10, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.0.11, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.0.12, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.0.13, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.0.14, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.0.15, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.0.2, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.0.3, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.0.4, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.0.5, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.0.6, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.0.7, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.0.8, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.0.9, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.1.0, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.1.0-BETA1, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.1.0-BETA2, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.1.0-BETA3, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.1.1, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.1.10, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.1.11, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.1.12, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.1.2, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.1.3, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.1.4, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.1.5, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.1.6, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.1.7, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.1.8, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.1.9, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.2.0, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.2.0-BETA1, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.2.0-BETA2, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.2.0-RC1, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.2.1, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.2.10, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.2.11, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.2.12, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.2.2, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.2.3, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.2.4, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.2.5, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.2.6, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.2.7, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.2.8, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.2.9, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.3.0, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.3.0-BETA1, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.3.0-BETA2, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.3.0-RC1, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.3.1, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.3.10, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.3.11, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.3.2, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.3.3, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.3.4, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.3.5, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.3.6, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.3.7, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.3.8, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.3.9, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.4.0, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.4.0-BETA1, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.4.0-BETA2, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.4.0-RC1, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.4.1, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.4.2, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.4.3, v5.0.2].
    - Can only install one of: symfony/css-selector[v4.4.4, v5.0.2].
    - Installation request for symfony/css-selector (locked at v5.0.2) -> satisfiable by symfony/css-selector[v5.0.2].

Installation failed, reverting ./composer.json to its original content.

C:\xampp\htdocs\project test\agrobint-test>

C:\xampp\htdocs\project test\agrobint-test>

C:\xampp\htdocs\project test\agrobint-test>php7.2 /usr/local/bin/composer require snowfire/beautymail dev-master
'php7.2' is not recognized as an internal or external command,
operable program or batch file.

C:\xampp\htdocs\project test\agrobint-test>

**Comment by emilsundberg** [comment]
Which version of Laravel are you using? I've just upgraded the emogrifier lib so it might work now.
