### ISSUE TITLE
Laravel 5.8 Update Error

### ISSUE THREAD

**Issue by CitizenBeta** [Snowfire/Beautymail#120]
I'm on the latest version of Laravel 5.8. I get this on running composer update. It doesnt help to downgrade versions either to an older commit. Any assistance would be greatly appreciated.

> Writing lock file
> Generating optimized autoload files
> ocramius/package-versions: Generating version class...
> ocramius/package-versions: ...done generating version class
> > Illuminate\Foundation\ComposerScripts::postAutoloadDump
> > @php artisan package:discover --ansi
> 
> In CssInlinerPlugin.php line 18:
>                                                                              
>   Call to undefined method Pelago\Emogrifier::disableInvisibleNodeRemoval()  
>                                                                              
> 
> Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
> 

I tried all of these:

> "snowfire/beautymail": "dev-master",

Then this:

> "snowfire/beautymail": "dev-master",
>  "pelago/emogrifier": "2.2.0",

Then this:

> "snowfire/beautymail": "dev-master#ffd8b385132c28f2428b76d0cc7bfe5565386485",
>  "pelago/emogrifier": "2.2.0",

None work.

**Comment by emilsundberg** [comment]
I’ll release a fix for this shortly. Please use the latest tagged release instead of dev-master to fix this issue right now

**Comment by CitizenBeta** [comment]
How do I do that? Setting the above in composer didn't work.

**Comment by emilsundberg** [comment]
Set a version on `composer.json` like this:
```
"snowfire/beautymail": "^1.0"
```

This issue has now been resolved with 942f8584135290a675944ed0d5c0e13c5e84031e
