### ISSUE TITLE
Laravel 7/8 compatibility

### ISSUE THREAD

**Issue by gfernandez-me** [Snowfire/Beautymail#128]
Hi,

any plans to update this package?

**Comment by emilsundberg** [comment]
It should work fine with Laravel 7. I haven't tried Laravel 8 yet but feel free to test it and submit a PR.

**Comment by shiroamada** [comment]
Is it ready to push to new version? @gfernandez-me thanks for the contribution

**Comment by filipbekic01** [comment]
This one is important.

**Comment by gfernandez-me** [comment]
> Is it ready to push to new version? @gfernandez-me thanks for the contribution

Yeah, it's working!

**Comment by emilsundberg** [comment]
Merged #129
