### ISSUE TITLE
Class App\Http\Controllers\Snowfire\Beautymail\Beautymail does not exist

### ISSUE THREAD

**Issue by anandatheerthan** [Snowfire/Beautymail#13]
I have added in provider array but getting error ReflectionException in Container.php line 736:
Class App\Http\Controllers\Snowfire\Beautymail\Beautymail does not exist

**Comment by phroggyy** [comment]
@anandatheerthan it looks to me like you aren't importing the Beautymail class in your controller. How are you using it? If you are writing out the FQCN in your code rather than using a `use` statement, make sure to add a leading backslash.

**Comment by anandatheerthan** [comment]
This is how I am using it and I am not getting error,"FatalErrorException in Beautymail.php line 37:
Unsupported operand types"
$beautymail = app()->make(\Snowfire\Beautymail\Beautymail::class);
		$beautymail->send('emails.order', $details, function($message)
		{
			$message
				->from('bar@example.com')
				->to('anand@an-t.in', 'John Smith')
				->subject('Welcome!');
		});

**Comment by phroggyy** [comment]
@anandatheerthan what do your `$details` look like? Also, please format your code with markdown in the future for readability.

**Comment by phroggyy** [comment]
Ah, I think I've found the problem. I'll fix it within an hour and you can try again after that.

**Comment by phroggyy** [comment]
@anandatheerthan this should be resolved now.

**Comment by anandatheerthan** [comment]
Hi, I now get error 
    ErrorException in Emogrifier.php line 269:
    DOMXPath::query(): Invalid expression

The $details is an array contains values.

**Comment by phroggyy** [comment]
@anandatheerthan is it the same one as the one your were trying above? I'll have a look at it tonight!

**Comment by anandatheerthan** [comment]
Yes its the same. 

Regards,
Anand

**Comment by anandatheerthan** [comment]
Hi Mate,
Did you get a chance to look into this issue.

**Comment by phroggyy** [comment]
@anandatheerthan sorry for not getting back to you, had a hectic time. If you still face this issue, could you post the full traceback here?

**Comment by bmoelk** [comment]
Getting the same when using the minty template:

ErrorException: DOMXPath::query(): Invalid predicate

/vendor/pelago/emogrifier/Classes/Emogrifier.php:723
/vendor/pelago/emogrifier/Classes/Emogrifier.php:683
/vendor/pelago/emogrifier/Classes/Emogrifier.php:329
/vendor/pelago/emogrifier/Classes/Emogrifier.php:217
/vendor/snowfire/beautymail/src/Snowfire/Beautymail/CssInlinerPlugin.php:31
vendor/swiftmailer/swiftmailer/lib/classes/Swift/Events/SimpleEventDispatcher.php:152
/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Events/SimpleEventDispatcher.php:132
/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:155
/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php:85
/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php:395
/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php:181
/vendor/snowfire/beautymail/src/Snowfire/Beautymail/Beautymail.php:58
.....

**Comment by azulkipli** [comment]
I got the 'ErrorException: DOMXPath::query(): Invalid predicate' issue too, when use minty template

**Comment by richardkeep** [comment]
Got the same error too. I wonder why no one is figuring out how to solve it

**Comment by phroggyy** [comment]
@richardkeep: the issue with the emogrifier?

**Comment by richardkeep** [comment]
Yes

Kind Regards,

Richard

**Comment by phroggyy** [comment]
@richardkeep: could you please open a new issue so I can close this one, as this one has so far taken up 3 issues, it would be helpful with one issue just describing the problem.

**Comment by emilsundberg** [comment]
I have pushed a fix for `ErrorException: DOMXPath::query(): Invalid predicate`. See #27
