### ISSUE TITLE
Using Beautymail with Laravel 8 and PHP 8.0.x required pelago/emogrifier

### ISSUE THREAD

**Issue by mwiesener** [Snowfire/Beautymail#132]
I found pelago/emogrifier on https://github.com/MyIntervals/emogrifierwith actual release 5.01 supporting PHP 8.0.
Beautymail require:
"pelago/emogrifier": "^3.0"
please check your reuirement to use  "pelago/emogrifier": "^5.0"

Thanks if possible

**Comment by emilsundberg** [comment]
Solved with #133
