### ISSUE TITLE
 pelago/emogrifier

### ISSUE THREAD

**Issue by dev-techguy** [Snowfire/Beautymail#135]
- pelago/emogrifier is locked to version v3.1.0 and an update of this package was not requested.
    - When using composer 2+ and php version (8.0.5)

**Comment by emilsundberg** [comment]
Try the latest tagged release which includes #131

**Comment by dev-techguy** [comment]
> Try the latest tagged release which includes #131

Getting this error.

![Screenshot from 2021-05-05 15-42-40](https://user-images.githubusercontent.com/36882600/117142974-fde28280-adb8-11eb-8861-6b9aa3c2e30b.png)

**Comment by lloricode** [comment]
> > Try the latest tagged release which includes #131
> 
> Getting this error.
> 
> ![Screenshot from 2021-05-05 15-42-40](https://user-images.githubusercontent.com/36882600/117142974-fde28280-adb8-11eb-8861-6b9aa3c2e30b.png)

same as mine after upgrading pelago/emogrifier (v3.1.0 => v5.0.1)

**Comment by lloricode** [comment]
adding this to composer.json will temporary solve the problem

```json
"pelago/emogrifier": "^3.1"
```

**Comment by dev-techguy** [comment]
> adding this to composer.json will temporary solve the problem
> 
> ```json
> "pelago/emogrifier": "^3.1"
> ```

Cant work with `php version (8.0.5) does not satisfy that requirement`

**Comment by lloricode** [comment]
> > adding this to composer.json will temporary solve the problem
> > ```json
> > "pelago/emogrifier": "^3.1"
> > ```
> 
> Cant work with `php version (8.0.5) does not satisfy that requirement`

i see, you are using php8, im using php74 while this is still issue

**Comment by lloricode** [comment]
check this

https://github.com/MyIntervals/emogrifier/blob/main/CHANGELOG.md#removed-2
https://github.com/MyIntervals/emogrifier/pull/774
https://github.com/Snowfire/Beautymail/blob/a4c86eea2339b2a0c5e3ab75d5507a4c07b942d8/src/Snowfire/Beautymail/CssInlinerPlugin.php#L17

**Comment by dev-techguy** [comment]
Guys, no fix on this issue has been released yet.

**Comment by dev-techguy** [comment]
> check this
> 
> https://github.com/MyIntervals/emogrifier/blob/main/CHANGELOG.md#removed-2
> [MyIntervals/emogrifier#774](https://github.com/MyIntervals/emogrifier/pull/774)
> https://github.com/Snowfire/Beautymail/blob/a4c86eea2339b2a0c5e3ab75d5507a4c07b942d8/src/Snowfire/Beautymail/CssInlinerPlugin.php#L17

Guys, no fix on this issue has been released yet.

**Comment by bashet** [comment]
> 
> 
> adding this to composer.json will temporary solve the problem
> 
> ```json
> "pelago/emogrifier": "^3.1"
> ```

This works for me. I am using Laravel 5.7, php 7.2

**Comment by dev-techguy** [comment]
> > adding this to composer.json will temporary solve the problem
> > ```json
> > "pelago/emogrifier": "^3.1"
> > ```
> 
> This works for me. I am using Laravel 5.7, php 7.2

But not working with Laravel 8+ and php 8.0.5

**Comment by emilsundberg** [comment]
The latest tagged version (v1.1.5) should solve this.

**Comment by dev-techguy** [comment]
> The latest tagged version (v1.1.5) should solve this.

Works, Cheers :)
