### ISSUE TITLE
Package Install Fail Laravel ^8.76.2

### ISSUE THREAD

**Issue by dev-techguy** [Snowfire/Beautymail#138]
Problem 1
    - snowfire/beautymail v1.1.3 requires pelago/emogrifier ^3.0 -> satisfiable by pelago/emogrifier[v3.0.0, v3.1.0, 3.1.x-dev].
    - snowfire/beautymail[v1.1.4, ..., v1.1.5] require pelago/emogrifier ^3.0|^4.0|^5.0 -> satisfiable by pelago/emogrifier[v3.0.0, v3.1.0, 3.1.x-dev, v4.0.0, v5.0.0, v5.0.1].
    - snowfire/beautymail 1.x-dev requires illuminate/support 4.*|5.* -> found illuminate/support[v4.0.0-BETA2, ..., 4.2.x-dev, v5.0.0, ..., 5.8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - snowfire/beautymail[v1.1.0, ..., v1.1.1] require illuminate/support 4.*|5.*|^6.0.0 -> found illuminate/support[v4.0.0-BETA2, ..., 4.2.x-dev, v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev] but these were not loaded, likely because it conflicts with another require.
    - snowfire/beautymail v1.1.2 requires illuminate/support 4.*|5.*|^6.0.0|^7.0.0 -> found illuminate/support[v4.0.0-BETA2, ..., 4.2.x-dev, v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but these were not loaded, likely because it conflicts with another require.
    - pelago/emogrifier[v3.1.0, ..., 3.1.x-dev] require php ^5.6 || ~7.0 || ~7.1 || ~7.2 || ~7.3 || ~7.4 -> your php version (8.0.13) does not satisfy that requirement.
    - pelago/emogrifier v3.0.0 requires php ^5.6.0 || ~7.0.0 || ~7.1.0 || ~7.2.0 || ~7.3.0 -> your php version (8.0.13) does not satisfy that requirement.
    - pelago/emogrifier v4.0.0 requires php ~7.0 || ~7.1 || ~7.2 || ~7.3 || ~7.4 -> your php version (8.0.13) does not satisfy that requirement.
    - pelago/emogrifier[v5.0.0, ..., v5.0.1] require symfony/css-selector ^3.4.32 || ^4.4 || ^5.1 -> found symfony/css-selector[v3.4.32, ..., 3.4.x-dev, v4.4.0-BETA1, ..., 4.4.x-dev, v5.1.0-BETA1, ..., 5.4.x-dev] but the package is fixed to v6.0.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires snowfire/beautymail ^1.1 -> satisfiable by snowfire/beautymail[v1.1.0, ..., 1.x-dev].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

**Comment by emilsundberg** [comment]
It looks like you are trying to install an older version? Try to install 1.1.15 instead of 1.1.13

**Comment by dev-techguy** [comment]
TypeError: array_merge(): Argument #1 must be of type array, null given in /home/techguy/PhpstormProjects/full-stack-template/vendor/snowfire/beautymail/src/Snowfire/Beautymail/BeautymailServiceProvider.php:53

**Comment by emilsundberg** [comment]
Follow the installation instructions in the readme.
