### ISSUE TITLE
PHP 8.1+ ERROR

### ISSUE THREAD

**Issue by dev-techguy** [Snowfire/Beautymail#140]
Problem 1
    - pelago/emogrifier is locked to version v5.0.1 and an update of this package was not requested.
    - pelago/emogrifier v5.0.1 requires php ~7.1.0 || ~7.2.0 || ~7.3.0 || ~7.4.0 || ~8.0.0 -> your php version (8.1.2) does not satisfy that requirement.
  Problem 2
    - pelago/emogrifier v5.0.1 requires php ~7.1.0 || ~7.2.0 || ~7.3.0 || ~7.4.0 || ~8.0.0 -> your php version (8.1.2) does not satisfy that requirement.
    - snowfire/beautymail v1.1.5 requires pelago/emogrifier ^3.0|^4.0|^5.0 -> satisfiable by pelago/emogrifier[v5.0.1].
    - snowfire/beautymail is locked to version v1.1.5 and an update of this package was not requested.

**Comment by dev-techguy** [comment]
How soon will this be resolved?

**Comment by emilsundberg** [comment]
I'm not using 8.1 yet. You are free to send a PR to solve this issue. I guess we need to upgrade our dependency on emogrifier to 6.

**Comment by dev-techguy** [comment]
Kindly.

**Comment by realtebo** [comment]
We too have a project locked down to laravel 8 due to dependency with this project and  (indirectly) with new pelago/emogrifier 

Please upgrade dependency

**Comment by gfernandez-me** [comment]
just need to change the composer json to something like this:

```
"require": {
        "php": ">=7.3.0",
        "pelago/emogrifier": "dev-main",
        "illuminate/support": "^9.17.0"
    },
```
    
    my fork: https://github.com/gfernandez-me/Beautymail/blob/master/composer.json

**Comment by lloricode** [comment]
https://github.com/Snowfire/Beautymail/issues/143#issuecomment-1272675977

**Comment by emilsundberg** [comment]
New release tagged
