### ISSUE TITLE
Need a new release - close after reading

### ISSUE THREAD

**Issue by robinlists** [Snowfire/Beautymail#143]
It looks like your `master` branch is already patched up, but the 1.1.5 release is having issues.

No need to respond - feel free to close after you receive this.

PS: I can't wait to try out your package, I'm getting excited!!!

If I pull from `dev-master` all is well.

`If I pull from 1.1.5 on Laravel 9.5.x I get:`

```Running composer update snowfire/beautymail
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires snowfire/beautymail 1.1.5 -> satisfiable by snowfire/beautymail[v1.1.5].
    - snowfire/beautymail v1.1.5 requires illuminate/support 4.*|5.*|^6.0.0|^7.0.0|^8.0.0 -> found illuminate/support[v4.0.0-BETA2, ..., 4.2.x-dev, v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.

```

**Comment by gfernandez-me** [comment]
I think the package itself is abandoned
I did a fork and changed the composer and I'm using mine from now on

**Comment by lloricode** [comment]
maybe you can use like this

```json

        "snowfire/beautymail": "dev-master",
```

then run `composer u`

@emilsundberg follow up for the release for this
