### ISSUE TITLE
PHP 8.1 Doesn't Support Beautymail

### ISSUE THREAD

**Issue by arif98741** [Snowfire/Beautymail#146]
![image](https://user-images.githubusercontent.com/17213478/184499292-90ab3d35-494d-41ae-b97b-d8edbd0b582d.png)

**Comment by lloricode** [comment]
https://github.com/Snowfire/Beautymail/issues/143#issuecomment-1272675977

**Comment by officialescrow247** [comment]
I noticed this error, i found a way around it; but here's the error i get when i try to send mails:
![image](https://user-images.githubusercontent.com/117183607/213368947-e4ccbdd8-6c0b-426e-a6eb-4859398d8ebb.png)

**Comment by cletuskingdom** [comment]
I found a way around "installing the package", but here's the error i get whenever I try sending a message:

![image](https://user-images.githubusercontent.com/38631504/213369189-5ef9369b-c15b-49d0-b54f-5a83bd3cb3a0.png)

Please who knows how i can solve this?

**Comment by arif98741** [comment]
> Please, upgrade this package !
> 
> We had a massive usage in a laravel 8 project and this is the only dep to do the missing upgrade

I already created a  [Pull Request](https://github.com/Snowfire/Beautymail/pull/151) to add support of laravel 8, 9 and also 10. Waiting for accepting and release new BeautyMail version

**Comment by emilsundberg** [comment]
Thanks @arif98741 👍

I’ve tagged a new release
