### ISSUE TITLE
Readme not correct for Laravel 5.0.33

### ISSUE THREAD

**Issue by SerbanC** [Snowfire/Beautymail#18]
Hi,

After some trial and error I managed to get Beautymail running on my Laravel 5.0.33 app, with the following change to the steps in your readme:

* In ```config/app.php```, if I put

   ```
   Snowfire\Beautymail\BeautymailServiceProvider::class,
   ```
   it throws the error:
   
   ```
FatalErrorException in ProviderRepository.php line 150:
Class 'Snowfire\Beautymail\BeautymailServiceProvider::class' not found
   ```

   The way it worked for me was to put (without `::class`)

   ```
   'Snowfire\Beautymail\BeautymailServiceProvider',
   ``` 

Also, I think some configuration steps are missing from the readme:
* In your own comment [here](https://github.com/Snowfire/Beautymail/issues/13#issuecomment-133322189) you mention importing the class into the controller (and I think this is probably a better practice than having the code in `routes.php` ) but there is no indication as to the actual line of code. This also implies (to my knowledge of Laravel) creating an alias in `config/app.php` which isn't covered at all. I inspected your package and tried creating aliases for either

   ```
'Beautymail' => 'Snowfire\Beautymail\BeautymailServiceProvider',
   ```
   or
   ```
'Beautymail' => 'Snowfire\Beautymail\Beautymail',
   ```
   then adding `use Beautymail;` in my controller, but both cases return `Undefined variable: beautymail`; So right now the only way I can use the class is via `$beautymail = app()->make(\Snowfire\Beautymail\Beautymail::class);` (with the initial `\` you mentioned in the linked comment).
* What is the empty array passed here: `$beautymail->send('emails.welcome', [], function($message)`? What can it contain and where do I write it?

**Comment by phroggyy** [comment]
Hey Serban,

1. Make sure that you place `Snowfire\Beautymail\BeautymailServiceProvider::class` **without** surrounding it by apostrophes. `::class` is PHP goodness for resolving the name of the class.
2. You do not need to create an alias, what was mentioned as `importing` was simply a reference to the `use` statement, which is used throughout Laravel so you should be familiar with it. You could actually just call `\Snowfire\Beautymail\Beautymail` in your controller if you don't want to have a `use Snowfire\Beautymail\Beautymail` before `class`.
3. The empty array is data passed to the view. Beautymail is just a wrapper around Laravel's `Mailer`, so you can simply read the documentation at http://laravel.com/docs/5.1/mail.

**Comment by SerbanC** [comment]
Hi Leo,

I did get it working by using `Snowfire\Beautymail\BeautymailServiceProvider::class` without quotes. Figured out the array as well, but I needed a little snooping inside the package code. Thanks
