### ISSUE TITLE
Mails content is empty

### ISSUE THREAD

**Issue by syphernl** [Snowfire/Beautymail#2]
If I try to send a mail with this package (or with the views provided actually) the mail content turns up empty. I have used the example from the readme.

**Comment by bgarrison25** [comment]
This is a real issue. Installing ruby just to have a working inliner makes this plugin unusable for me and many others. Any news on an alternative?

**Comment by emilsundberg** [comment]
@bgarrison25 No, sorry but I'm open to pull requests!

**Comment by bgarrison25** [comment]
I have put in a pull request to an inliner that works well and does not require ruby.
