### ISSUE TITLE
Undefined variable: logo

### ISSUE THREAD

**Issue by shanka12** [Snowfire/Beautymail#20]
Hi
I am getting following error message. How do I fix?

Undefined variable: logo
\vendor\snowfire\beautymail\src\views\templates\minty.blade.php

**Comment by phroggyy** [comment]
@shanka12 This would be because you don't pass through any logo variable to the view. Either you modify the template to not include a logo, or pass the logo through.

**Comment by SadiqUltra** [comment]
$logo = Config::get('beautymail.logo');

and pass $logo

**Comment by phroggyy** [comment]
@shanka12 @sadiqultra: what you can also do is create a view composer for all email views to automatically pass through the variable. Alternatively, using the Beautymail mailer rather than Laravel's own
