### ISSUE TITLE
Config file: css ignored

### ISSUE THREAD

**Issue by tiboufroulou** [Snowfire/Beautymail#22]
'css' section of the published config file is ignored. This is due to the fact you are passing beautymail.view as parameter of Beautymail service constructor :)

**Comment by antongorodezkiy** [comment]
+1

In my case I didn't use `$beautymail = app()->make(Snowfire\Beautymail\Beautymail::class);` currently and used Laravel's `Mail` instead, but with Beautymail's templates:

```
$data = array_merge(
            $data,
            config('beautymail.view'),
            [
                'css' => implode(' ', config('beautymail.css'))
            ]
        );
        
        Mail::send('emails.user.welcome', $data, function ($m) use ($user, $subject) {
        ...
```

**Comment by emilsundberg** [comment]
Feel free to send a PR to fix this!

**Comment by ecuation** [comment]
a fast solution for me was add 'css' into the "view" array in the beautymail.php configuration file:

   ```
 'view' => [
        'css'         => file_get_contents(dirname(__FILE__) . '/../public/css/beautymail.css'),
      //...
    ],
```

and it works.

**Comment by PENDOnl** [comment]
I'm on this.. almost got it covered. However, the $css variable doesn't seem to get set within the <style> tags. Currently testing some things and hopefully I'll have a working PR ready soon

**Comment by PENDOnl** [comment]
I think I figured it out, tested and created a pull request (https://github.com/Snowfire/Beautymail/pull/50). I noticed not everything worked but that's a different issue.
