### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by heremiguel** [Snowfire/Beautymail#3]
Hi, 
I followed the steps but I didn't get installed.
1. When you said add to composer.php you mean add to composer.json to "require" section?
2. I added to composer.json and got this error:
 [RuntimeException]                                                                                                                                                                              
  Error Output: PHP Fatal error:  Class 'Snowfire\Beautymail\BeautymailServiceProvider' not found in /lamp/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 157

3. Do I need to download anything and copy to any folder?
and finally:
4. If I run php artisan asset:publish "snowfire/beautymail" always got:
PHP Fatal error:  Class 'Snowfire\Beautymail\BeautymailServiceProvider' not found in /lamp/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 157
{"error":{"type":"Symfony\\Component\\Debug\\Exception\\FatalErrorException","message":"Class 'Snowfire\\Beautymail\\BeautymailServiceProvider' not found","file":"\/lamp\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/ProviderRepository.php","line":157}}

Thank you very much for your help.

**Comment by emilsundberg** [comment]
1) Yes to the required section. You will also need to run `composer update` after you've edited composer.json

**Comment by heremiguel** [comment]
Thank you very much mate! everything work.
I think you need to clarify when you update composer.json instead composer.php you have to run composer update. Maybe it's obvious but more info is good than less. ;)
Thank you
