### ISSUE TITLE
Domain isn't set in queued job

### ISSUE THREAD

**Issue by jhoff** [Snowfire/Beautymail#30]
If you use Beautymail in a queued job, Request::getSchemeAndHttpHost() returns http://localhost by default, which means all images will be broken.

See this for reference: http://stackoverflow.com/questions/28373730/getting-route-url-from-queue-returns-wrong-base

Perhaps instead of relying on Request::getSchemeAndHttpHost(), we could use an injected view variable that either uses the Request or defaults to Config::get('app.url') when it's running as a Job?

**Comment by jhoff** [comment]
Disregard. Laravel already falls back to the url in config/app.php. I just forgot to set it. :/

**Comment by gabrielsch** [comment]
@jhoff How did you solve it?

**Comment by jhoff** [comment]
Set the `url` parameter in `config/app.php`
