### ISSUE TITLE
It's not showing logo or FB icons

### ISSUE THREAD

**Issue by freel132** [Snowfire/Beautymail#36]
I have default installation. but there is not showing logo and social media logo.. 

and working by default only 'widgets' template, other giving me error logo not found...
Any idea what is wrong? Using laravel 5.2

**Comment by phroggyy** [comment]
How have you specified your logo?

**Comment by Luceos** [comment]
@freel132 my guess is you haven't published the assets of this package yet __or__ you are working on a  local environment (which is not accessable by your mail client).

**Comment by freel132** [comment]
thats correct. it was local environment. thx

**Comment by Hesesses** [comment]
I have a logo in .svg format and its not shown... jpg file works fine.

Any ideas why this is happening?
