### ISSUE TITLE
Pass {{ url() }}

### ISSUE THREAD

**Issue by lstables** [Snowfire/Beautymail#37]
Unable to pass ````{{ url() }}```` through to the class.

**Comment by phroggyy** [comment]
Could you expand on where you're trying to pass this?

**Comment by lstables** [comment]
So I the following:

````
@extends('beautymail::templates.widgets')

@section('content')

    @include('beautymail::templates.widgets.articleStart')
    <h4 class="secondary">Hi, {{ $fname }}</h4>
    <p class="lead">We thought your should know....</p>

    <p>
        Your campaign "<strong>{{$campaign}}</strong>" has been inactive for 7 days or more
    </p>
    <p>You can login <a href="https://domain.com">here</a> to re-start your campaign.</p>

    @include('beautymail::templates.widgets.articleEnd')

@stop
````

The a href is where I want to pass ````{{ url() }}```` to

**Comment by phroggyy** [comment]
Alright, and what error are you seeing?

**Comment by lstables** [comment]
htmlentities() expects parameter 1 to be string, object given (View: /home/vagrant/code/moberce/resources/views/emails/campaigns/overdue.blade.php)

**Comment by lstables** [comment]
My bad I needed to pass a param to it: ````{{ url('/') }}````
