### ISSUE TITLE
Minty template doesn't read the color values in the config file properly

### ISSUE THREAD

**Issue by spinner2727** [Snowfire/Beautymail#38]
No matter what I did, I couldn't get the Minty template to respect the colors I was putting in the config/beautymail.php file.  After looking in the minty.blade.php template file in the vendor src folder, I see it's pulling the values from Config::get('beautymail**::templates**.color.highlight'), which is null when I try to print it out.  Changing this to Config::get('beautymail.color.highlight') fixed it for me, but I do not know if this is the proper way to fix it (I doubt it).  Anyone else experiencing this?

**Comment by jaumeavila** [comment]
Yeah, the same here...

**Comment by phroggyy** [comment]
@spinner2727 you are right. It is the proper way to fix it afaik, that's how configs work, must be a mistake from our side! It'd be great if you could just PR the change :)

**Comment by PENDOnl** [comment]
I found a few things in the templates that doesn't seem to be right. The configuration settings aren't used across the templates at all. At least, it doesn't seem to work for me at all. I forked the repo and changed what @spinner2727 has requested, but I don't believe that fixes all issues concerning the colors and logo's used in the templates, does it?

**Comment by PENDOnl** [comment]
Nevermind, that was a fault on my side. I'll create a PR with the changes as given by @spinner2727

**Comment by emilsundberg** [comment]
Thanks for the fix @PENDOnl 👍

**Comment by PENDOnl** [comment]
Issue can be closed by the way 👍
