### ISSUE TITLE
Display template in view

### ISSUE THREAD

**Issue by bikedel** [Snowfire/Beautymail#40]
Hello thanks for the great work.

How do I display the email template in a view instead of sending it?

**Comment by phroggyy** [comment]
Hey,

Since it's just a normal blade template, you can use it just like any other blade template. Just create your blade file and return the view from a route.

**Comment by bikedel** [comment]
Thanks but when I do that none of the data I pass is displayed like in the sent mail.
What am I doing wrong?
Thanks

From my controller:

        $data = array(
            'senderName'  => null, // Company name
            'reminder'    => 'You’re receiving this because....... Visit  <a href="http://www.domain.co.za/" style="color: #a6a6a6">our site</a>',
            'unsubscribe' => null,
            'address'     => 'Protea Street, Claremont, Cape Town',
            'twitter'     => 'http://www.facebook.com/Sotherby',
            'facebook'    => 'http://twitter.com/Sotherby',
            'flickr'      => 'http://www.flickr.com/photos/Sotherby',
        );
        return view('emails.template_welcome', compact('data'));

**Comment by warmwhisky** [comment]
Same for me. When I pass it to a view its fails. I get the following error...

`Undefined variable: css `

**Comment by raymondTheDev** [comment]
You can try this:

```
return view('emails.template_welcome', [
   'css' => '',
   'logo' => [],
]);
```
