### ISSUE TITLE
Support for Lumen?

### ISSUE THREAD

**Issue by mikerockett** [Snowfire/Beautymail#42]
Any chance support for Lumen could be added?

Presently, running the `vendor:publish` command results in the following fatal exception:

> `[Symfony\Component\Debug\Exception\FatalErrorException]`
> Call to undefined function `Snowfire\Beautymail\config_path()` in `vendor\snowfire\beautymail\src\Snowfire\Beautymail\BeautymailServiceProvider.php` on line 24

**Comment by mikerockett** [comment]
So I've manually published the assets and config and have created the necessary helpers file for the `config_path` and `public_path`. Now, however, I'm running into this problem:

> `BindingResolutionException` in `Container.php` line 752:
> Target `[Illuminate\Contracts\Mail\Mailer]` is not instantiable.

I installed `illuminate/mail` and I use it like this:

```php
app('mailer')->send(...)
```

**Comment by mikerockett** [comment]
Hmm, I think I'm going to land up switching the app over to Laravel... It's a really small app, which is why I chose Lumen, but every time I find a fix/workaround for an issue, another one pops up...

**Comment by emilsundberg** [comment]
I've never used Lumen but if someone is up for making this package work with Lumen I'll happily accept a PR :)

Btw every time we have been thinking about Lumen in an app/utility we have always ended up with Laravel. It's so much less hassle.

**Comment by mikerockett** [comment]
> Btw every time we have been thinking about Lumen in an app/utility we have always ended up with Laravel. It's so much less hassle. 

That is very true. It's a pity they took email out of the picture with Lumen - micro-services should be able to make use of email, and everything should be built in the same way it is with Laravel. I've switched over now, anyway, and the module is working great. Unfortunately, however, the templates don't appear to be compatible with Outlook 2013 (don't have another version to test on, but I'm sure they'd all be the same). So I've gone and used Mailgun's templates, which suite my needs perfectly.

**Comment by emilsundberg** [comment]
@mikerockett Did you try the sunny template? It should be compatible with Outlook 2013.

**Comment by mikerockett** [comment]
I did indeed try it, and may land up going back to it if the Mailgun template I'm using now doesn't pan out.

**Comment by svenhakvoort** [comment]
I found out a way to get this extension working on lumen with a few (relatively) easy additions, I could write a README for this if this is useful for you?

**Comment by emilsundberg** [comment]
@svenhakvoort Feel free to add a section to the README as a PR for how to get this package running on Lumen :)
