### ISSUE TITLE
Class App\Http\Controllers\Snowfire\Beautymail\Beautymail does not exist

### ISSUE THREAD

**Issue by ruthannedilig** [Snowfire/Beautymail#43]
Hi, i successfully installed the beauty mail in my laravel instance but I get this error..

here's my code

$beautymail = app()->make(Snowfire\Beautymail\Beautymail::class);
                        $beautymail->send('emails.booking-confirmation', $arData, function($m) use ($user) {
                             $m->to($user->email, $user->first_name . ' ' . $user->last_name);
                             $m->subject('Booking Confirmation from Wave House Sentosa');    
                        });

**Comment by emilsundberg** [comment]
Try adding a \ before Snowfire like this: 

`\Snowfire\Beautymail\Beautymail::class`

**Comment by phroggyy** [comment]
This is a referencing error, with the solution demonstrated by @emilsundberg. Another solution is placing `use Snowfire\Beautymail\Beautymail;` at the top of your class file and then just using `app(Beautymail::class)` (`app('something') is shorthand for `app()->make('something')`. Last but not least, you could also use the string: `app('Snowfire\Beautymail\Beautymail')`.

Closing this now as I believe we have more than enough solutions to pair everyone's tastes :)

**Comment by OAmor** [comment]
yes it's really working by adding a \ before , but can i know why ??
