### ISSUE TITLE
Changing subject title dynamically and pushing data into the view

### ISSUE THREAD

**Issue by pknad505** [Snowfire/Beautymail#54]
Hello I am trying to push data into the subject of $message however i keep getting that this variable doesn't exist and i cant work out how to fix it.
Here is a look at my function:
```

    $name = (DB::table('base_projects_databases')->select('name')->where('id','=', $request->projectID)->get())[0]->name;

    $beautymail = app()->make(\Snowfire\Beautymail\Beautymail::class);
    $beautymail->send('emails.newIssue', ["project" => $name], function($message)
    {
      $message
      ->from('notifier@yetanotherissuetracker.com')
      ->to('admin@yetanotherissuetracker.com', 'Dan Marks')
      ->subject('New Issue Created For: ' . $project);
    });
```

**Comment by pknad505** [comment]
Also how do i get data from my controller into the view before it sent

**Comment by sevenpointsix** [comment]
I believe you'll need to pass $project into your closure, something like this:

    $beautymail->send('emails.newIssue', ["project" => $name], function($message) use ($project)
        {

**Comment by msbir** [comment]
Hey, Any solution for passing data inside the view from the controller?

**Comment by emilsundberg** [comment]
#80
