### ISSUE TITLE
Use Beautymail on top of Laravel 5.3 mailables

### ISSUE THREAD

**Issue by infernobass7** [Snowfire/Beautymail#56]
I was looking into a way to make beautymail work on top of the mailables. This is what I was able to come up with. I would love to see people's thoughts on the matter

```
<?php

namespace App\Mail;

use Illuminate\Mail\Mailable;
use Illuminate\Container\Container;
use Illuminate\Contracts\Mail\Mailer as MailerContract;
use Snowfire\Beautymail\Beautymail;

class BeautyMailable extends Mailable
{

	/**
	 * Send the message using the given mailer.
	 *
	 * @param  \Illuminate\Contracts\Mail\Mailer  $mailer
	 * @return void
	 */
	public function send(MailerContract $mailer)
	{
		Container::getInstance()->call([$this, 'build']);

		$beautymail = app()->make(Beautymail::class);

		$beautymail->send($this->buildView(), $this->buildViewData(), function ($message) {
			$this->buildFrom($message)
				->buildRecipients($message)
				->buildSubject($message)
				->buildAttachments($message)
				->runCallbacks($message);
		});
	}
}
```

**Comment by xitude** [comment]
I have just started work on the same task. I'll give you suggestion a go and feedback if I can improve.

**Comment by xitude** [comment]
If do you the suggested @infernobass7 then replace `Mailable` and extend the `BeautyMailable` class you can get this to work. Thanks for the suggestion.

**Comment by jgbneatdesign** [comment]
Wouldn't it be simpler if Beautymail could simply hook itself in the View layer rather than replace the Mail class? I send it could be easier for compatibility with future versions of the framework. I'm on 5.3 now and soon 5.4 on a project and I wanted to send beautify emails with this package. But now with Mailables I just can't do it (easily). I think this package could just provide some templates and that's it. It would be better for everyone.

**Comment by vesper8** [comment]
@xitude 

Hey thanks for trying to explain but I am confused by what you wrote

```
If do you the suggested @infernobass7 then replace Mailable and extend the BeautyMailable class you can get this to work. Thanks for the suggestion.
```

What did you mean? in his example he extends his BeautyMailable with Mailable. So what you said doesn't really make sense to me.

Can you post a final working example of how you are using mailables with this package?

@emilsundberg

Is there any chance this package will be updated to have a cleaner integration with Laravel's Mailables? I think that would be helpful to keep it relevant and used on new installations

**Comment by emilsundberg** [comment]
I'm open to the idea! We're still on 5.2 so I haven't had the time to investigate how to change this package to work with Mailable. 

We will eventually get there, but I'm open to accepting PRs :)

**Comment by xitude** [comment]
@vesper8 

1. create a mail called `php artisan make:mail BeautyMailable`
2. paste @infernobass7's code inside
3. Create the mail you want to wrap and send e.g. php artisan make:mail ExampleMail`
4. Replace the `class ExampleMail extends Mailable` with `class ExampleMail extends BeautyMailable`
5. Make sure you import the class

This should let you create a mail with the BeautyMailable wrapper.

**Comment by xitude** [comment]
Also this is now a thing https://laravel-news.com/email-themes

**Comment by Binternet** [comment]
@infernobass7 it seems the code throws an `ErrorException`:

`Undefined variable: logo`
