### ISSUE TITLE
is it compatible with 5.4?

### ISSUE THREAD

**Issue by kiwo12345** [Snowfire/Beautymail#59]

**Comment by emilsundberg** [comment]
I don't know. I haven't tried 5.4 yet, but feel free to do so and report back to us :)

**Comment by xitude** [comment]
See #56

**Comment by ikbelkirasan** [comment]
Yes, I've just sent an email using it with Laravel 5.4. No issues so far.

**Comment by t-pankajkumar** [comment]
Unable queue mails using BeautyMail.

`Uncaught exception 'InvalidArgumentException' with message 'Only mailables may be queued.' in /opt/lampp/htdocs/Test/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php:314`

**Comment by ediblemanager** [comment]
@t-pankajkumar created a new issue for this [https://github.com/Snowfire/Beautymail/issues/85](url)
