### ISSUE TITLE
Dependency for composer

### ISSUE THREAD

**Issue by brentnd** [Snowfire/Beautymail#6]
I couldn't get composer to install beautymail. I have a Laravel 5 installation.

Only emil/inlier [dev-master] has support for Laravel 5, but snowfire/beautymail [dev-master] requires emil/inliner [1.*] which doesn't work for Laravel 5.

**Comment by emilsundberg** [comment]
I have updated inliner to work with L5 so Beautymailer should be installable on L5. If the package needs more adjustments in L5, feel free to make PR.

**Comment by emilsundberg** [comment]
I have made this package Laravel 5 compatible now if you use dev-master
