### ISSUE TITLE
How do we create new templates?

### ISSUE THREAD

**Issue by xitude** [Snowfire/Beautymail#61]
I know I could just create a blade template and extend it, but I would like to know how *you* would like us to extend and create templates. Since there is zero documentation on this subject.

**Comment by emilsundberg** [comment]
Yeah we need to find some kind of system for templates. There is no documentation since there is no good way to do it.

Our initial thoughts were to include great templates out of the box. And keep them inside the Beautymail repo to make sure we can update them to fix bugs and layouts issues. 

It feels like there is a better way to do it. And maybe you should copy the template to your own project to be free to do whatever you want with a template.

I'm open to suggestions.

**Comment by xitude** [comment]
I resorted to building a template directory in my email views and extended that, but I feel like it defeats the point of Beautymail

**Comment by Hesesses** [comment]
any updates on this?

**Comment by OctaneInteractive** [comment]
Hi @xitude, how did you accomplish this? I ask because, having done the integration, I was expecting documentation explaining how to publish a custom template.

**Comment by xitude** [comment]
@OctaneInteractive this was over a year ago, I now just extend the Laravel Default Markdown Notifications for Mail, Blade files via `php artisan vendor:publish --tag=laravel-notifications` quite a few tutorials are about. (Officially Here)[https://laravel.com/docs/5.5/notifications#customizing-the-templates]

**Comment by OctaneInteractive** [comment]
@xitude, I appreciate this was some time ago, but this problem persists.

So do I move the Blade files I've created into the `resources/views/vendor/notifications/` folder, and if so, what about the `beautymail::templates` path, or do I ignore that and use something else?

**Comment by xitude** [comment]
@OctaneInteractive ill most likely have to readd this to a new project and refigure it out. What version of laravel are you on?

**Comment by OctaneInteractive** [comment]
@xitude, Laravel 5.6

**Comment by xitude** [comment]
Ill start a new repo now and reattempt it. Ill update you soon.

**Comment by xitude** [comment]
@OctaneInteractive also over a year ago I inputted in this issue. It might help.
https://github.com/Snowfire/Beautymail/issues/56

**Comment by xitude** [comment]
Something that is annoying me while I reattempt this, is Laravel 5.6 [Mail](https://laravel.com/docs/5.5/notifications) has themes and documentation on [how to theme](https://laravel.com/docs/5.5/notifications#customizing-the-templates) your transactional mail. Im pretty sure this package is obsolete.
