### ISSUE TITLE
How can i change this blue bar color?

### ISSUE THREAD

**Issue by arturcesarmelo** [Snowfire/Beautymail#65]
![captura de tela 2017-08-07 as 16 55 43](https://user-images.githubusercontent.com/18191910/29043380-52a5dcbc-7b91-11e7-8564-72587f253ca0.png)

**Comment by emilsundberg** [comment]
If you publish the config you should be able to change it there. See the readme section called 'Publish assets to your public folder'.

colors => highlight => #004ca3
