### ISSUE TITLE
PHP error on class Beautymail.php line 7

### ISSUE THREAD

**Issue by filjoseph1989** [Snowfire/Beautymail#71]
I just upgraded laravel from 5.4 to 5.5.3 but when I run php artisan SendNotification:notifications on command line I got this.
```
PHP Fatal error:  Class Snowfire\Beautymail\Beautymail contains 2 abstract methods and must th
erefore be declared abstract or implement the remaining methods (Illuminate\Contracts\Mail\Mai
ler::to, Illuminate\Contracts\Mail\Mailer::bcc) in C:\laragon\www\liz\vendor\snowfire\beautyma
il\src\Snowfire\Beautymail\Beautymail.php on line 7
```

I am making notification in the background process, and you package break on 5.5.3 Laravel version,
it's working on laravel 5.4

**Comment by phroggyy** [comment]
@filjoseph1989 As of 5.5, the Mailer contract has changed. I'll try to resolve this today or tomorrow. We'll have to publish a new major version as this is a breaking change.

Just a note for myself:

- new patch release setting a stricter constraint of `4.*|<= 5.4`
- new major release with `illuminate/support: ^5.5` and new contract implementation

**Comment by lstables** [comment]
@phroggyy Is this now fixed as I'm having the same issue with 5.5?

**Comment by cliffordy** [comment]
@phroggyy Anyluck?

**Comment by vesper8** [comment]
@phroggyy running into same issue.. is fix around the corner? :)

**Comment by timothyallan** [comment]
Aaaand I just hit this as well.

**Comment by floreean** [comment]
Same here!

**Comment by jamest-nz** [comment]
Here is a possible fix, which makes Beautymail work for me under Laravel 5.5.17 / PHP 7.0.24.

I'm not sure if my method implementations are correct, but at the very least your scripts will now run without complaining about unimplemented methods. My basic use-case of sending out email invitations to newly signing-up users now works well after applying the below patch.

Edit file at: vendor/snowfire/beautymail/src/Snowfire/Beautymail/Beautymail.php

Add following two methods to this file:

    public function to($users)
    {
        return (new PendingMail($this))->to($users);
    }

    public function bcc($users)
    {
        return (new PendingMail($this))->bcc($users);
    }


You could also try empty method implementations (or returning null) rather that what I've done above. As long as you implement the two methods above, it might not matter what they actually do, as the following way of sending emails (which is what I'm doing) doesn't seem to call them:


    $beautymail->send('emails.mytemplate', array('somedata' =>$data), function($message)
    {
        $message->from('me@me')
			->to('you@you', 'You')
			->subject("Hello there");
    });


Hope this helps someone.

**Comment by emilsundberg** [comment]
Thanks for your contribution @jamest-nz. Please note that it isn't recommended changing files in the vendors directory. 

Please submit a PR with your changes and more people can try your fix and see if it works.

**Comment by emilsundberg** [comment]
I've merged a PR with the missing methods now. See #77

**Comment by cliffordy** [comment]
Works Perfect... Thanks!

**Comment by apysais** [comment]
Is this fix? im getting an error after upgrading to Laravel 5.5
