### ISSUE TITLE
CssInlinerPlugin

### ISSUE THREAD

**Issue by ajwise0521** [Snowfire/Beautymail#72]
I am continuously getting the error from BeautyMailServiceProvider.php that 'Skipped Registering the SwiftMailer plugin: CssInlinerPlugin. I have no idea why and i've tried multiple approaches to get rid of it. Any ideas?

**Comment by gfernandez-me** [comment]
Need to update the pelago emogrifier dependency 

https://github.com/gfernandez-me/Beautymail/commit/f564b65a51d25f9bcf23c23bbe89d26b9e50d92e

**Comment by gfernandez-me** [comment]
lol, still not working

**Comment by emilsundberg** [comment]
The latest version is now using the new Emogrifier syntax

**Comment by itailulu** [comment]
I'm still getting this with PHP 8.1.11 and Laravel 9.5
Anyone figured out how to fix this?

**Comment by JaZo** [comment]
I've found the cause and opened #152 with a fix.
