### ISSUE TITLE
Class 'Snowfire\Beautymail\BeautymailServiceProvider' not found

### ISSUE THREAD

**Issue by amazingdetective** [Snowfire/Beautymail#75]
Not sure if I am being extremely silly or not, but been a tiring couple of days.

Similar issue as here: https://github.com/Snowfire/Beautymail/issues/3

I have done: 

```
composer require snowfire/beautymail dev-master
Added Snowfire\Beautymail\BeautymailServiceProvider::class, to providers in config/app.php
```

And attempted:

```
php artisan vendor:publish --provider="Snowfire\Beautymail\BeautymailServiceProvider"
```
Which results in:   
```
[Symfony\Component\Debug\Exception\FatalThrowableError]
  Class 'Snowfire\Beautymail\BeautymailServiceProvider' not found
```

I tried composer update, which results in:
```

  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Class 'Snowfire\Beautymail\BeautymailServiceProvider' not found

Script php artisan optimize handling the post-update-cmd event returned with error code 1
```

It is not a new project I am working on, and it is entirely possible someone already installed this before, as there is a beautymail.php in the config folder. 

However still not sure why I am then getting composer update errors still. Any feedback appreciated.

**Comment by warmwhisky** [comment]
I get this error on my remote server. Cannot composer update or install?
I'm stuck!

**Comment by mobiblunt** [comment]
i'm also getting this error.

**Comment by anandkumar144** [comment]
me too.

**Comment by InspiredPrynce** [comment]
Its killing us, please reply

**Comment by emilsundberg** [comment]
Has anyone tried to solve this issue? Please let me know which version av Laravel you are running and that you are using the latest dev-master in your composer and I'll take a look.

**Comment by InspiredPrynce** [comment]
Running Laravel 5.4 and i just installed the snowfire dev-master today

"require": {
        "php": ">=5.6.4",
        "doctrine/dbal": "^2.5",
        "guzzlehttp/guzzle": "^6.3",
        "laravel/framework": "5.4.*",
        "laravel/tinker": "~1.0",
        "snowfire/beautymail": "dev-master"
    }

**Comment by anandkumar144** [comment]
"require": {
        "php": ">=5.6.4",
        "acacha/admin-lte-template-laravel": "4.*",
        "barryvdh/laravel-dompdf": "^0.8.1",
        "laravel/framework": "5.4.*",
        "laravel/tinker": "~1.0",
        "nwidart/laravel-modules": "^1.27",
        "pear2/net_routeros": ">=1.0.0b6",
        "pear2/net_transmitter": ">=1.0.0b1",
        "snowfire/beautymail": "dev-master"
    }

**Comment by amazingdetective** [comment]
@emilsundberg 

Working for me now, not sure what fixed it but nothing specific has changed on my side, getting no errors any longer though. Maybe it was the tiredness.  

Using laravel 5.4, and dev-master beautymail. Went through the exact process as the opening post. Working now.

**Comment by InspiredPrynce** [comment]
I have fixed mine...
I removed the whole vendor directory and ran composer install and it worked like a charm....

**Comment by InspiredPrynce** [comment]
Started a new project again and the problem started again. Please help

**Comment by warmwhisky** [comment]
Arghh I must remember not to use this package as it seems to have more trouble than anyone fixing. This had me stuck again! 

I fixed it by renaming bootstrap/cache/config.php

Only then was I able to uninstall and use php artisan commands again.

**Comment by LuChungHeng** [comment]
Yes to the required section. You will also need to run `composer update` after you've edited composer.json
