### ISSUE TITLE
Unable to get it working in 5.5

### ISSUE THREAD

**Issue by ghost** [Snowfire/Beautymail#76]
I get the following error:
```
[Symfony\Component\Debug\Exception\FatalErrorException]                                                                                                                                                                    
  Class Snowfire\Beautymail\Beautymail contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (Illuminate\Contracts\Mail\Mailer::to, Illuminate\Contracts\Mail\Mailer::bcc)
```

Could you please bring an update for the latest laravel version?

**Comment by anantaramdas** [comment]
I found that it was resolved in https://github.com/Snowfire/Beautymail/issues/71 and pulled in https://github.com/Snowfire/Beautymail/pull/77 (you could check for your reference :) ).

After changing in composer to `dev-master`:
```
...
"snowfire/beautymail": "dev-master",
...
```
and running `composer update` it resolved issue.
