### ISSUE TITLE
Data on view

### ISSUE THREAD

**Issue by msbir** [Snowfire/Beautymail#80]
How do I get data to the view from the controller?

my controller - 

$order = $this->order;

$beautymail = app()->make(Beautymail::class);

$beautymail->send('mails.orderNotification', [], function($message)
    {
      $message
        ->from('someone@gmail.com')
        ->to('text@gmail.com', 'Jon Due')
        ->subject('Welcome');
    });

How can I pass the $order?

**Comment by emilsundberg** [comment]
Something like this:

```php
$order = $this->order;

$beautymail = app()->make(Beautymail::class);

$beautymail->send('mails.orderNotification', [], function($message) use ($order) {
   $message
      ->from('someone@gmail.com')
      ->to('text@gmail.com', 'Jon Due')
      ->subject('Welcome, Order Id: '.$order->id);
});
```

More info here: http://php.net/manual/en/functions.anonymous.php

**Comment by msbir** [comment]
Thank you for the answer.

Maybe I wasn't clear enough,
I want to get the $order to the template view.

If normally I will do
view('mails.orderNotification',compact('order'));

How can I do it here?

**Comment by emilsundberg** [comment]
Ah, try

```php
$beautymail->send('mails.orderNotification', ['order' => $order], function($messa..
```

**Comment by msbir** [comment]
Thank you!

**Comment by AndyDunn** [comment]
Could you maybe include this in the docs as part of the examples?
