### ISSUE TITLE
somehow the latest version of pelago/emogrifier is not being fetched, broken on PHP 7.2

### ISSUE THREAD

**Issue by vesper8** [Snowfire/Beautymail#82]
I can't figure out why this is happening.

If I install pelago/emogrifier dev-master manually then it installs the latest dev-master commit

but when I install the snowfire/beautymail dev-master, even though ti has a dependency on pelago/emogrifier @dev, in my installation it doesn't get the latest version which leads to an error because the latest version it does get (1.2.0) is not compatible with PHP 7.2

**Comment by oliverklee** [comment]
I recommend using the `^2.0.0` version constraint instead. Thus, you have the (now) current version, but will not get any breaking changes by accident.

**Comment by emilsundberg** [comment]
Fixed with #112
