### ISSUE TITLE
Problem removing Beautymail

### ISSUE THREAD

**Issue by OctaneInteractive** [Snowfire/Beautymail#88]
Hi, I ran the command: `composer remove snowfire/beautymail` and got the following:

> Package "snowfire/beautymail" listed for update is not installed. Ignoring.
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Package operations: 0 installs, 0 updates, 1 removal
>   - Removing snowfire/beautymail (dev-master)
>     The package has modified files:
>     AM src/styles/css/tobook.css
>     AM src/views/templates/tobook.blade.php
>     AM src/views/templates/tobook/contentEnd.blade.php
>     AM src/views/templates/tobook/contentStart.blade.php
>     Discard changes [y,n,v,d,?]? y
> Writing lock file
> Generating optimized autoload files
> > Illuminate\Foundation\ComposerScripts::postAutoloadDump
> > @php artisan package:discover
> 
> In ProviderRepository.php line 208:
>                                                                    
>   Class 'Snowfire\Beautymail\BeautymailServiceProvider' not found  
>                                                                    
> 
> Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1
> 
> Removal failed, reverting ./composer.json to its original content.

While this hasn't caused problems on the development version, it's killed staging.

I've tried running: `composer update` and: `composer clearcache` but it's made no difference.

**Comment by emilsundberg** [comment]
Try removing it manually from `composer.json` and then run a `composer update`

**Comment by OctaneInteractive** [comment]
Yeah, that's what I did in the end.
