### ISSUE TITLE
Can't change the logo without editing the /vendor directory?

### ISSUE THREAD

**Issue by iamgoodbytes** [Snowfire/Beautymail#9]
Hi! I'd like to use the minty template, but can't seem to change the logo without changing the contents of the vendor directory. Of course, changing the vendor directory isn't something I want to do as that would break future updates of Beautymail. 

What would you suggest? Thanks a lot.

Joris

**Comment by iamgoodbytes** [comment]
Just noticed that the vendor folder is inside the /public folder, sorry about that!

**Comment by emilsundberg** [comment]
Np :)
